name: Sync with GitLab

on:
  push:
    branches:
      - main

jobs:
  sync_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Sync with GitLab
        run: |
          git remote add gitlab https://oauth2:glpat-wPvGW8AndrDwcwKAoc9P@gitlab.com/abhishek73025/test_repo.git
          git push gitlab main
