name: Sync GitHub to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Git configuration
        run: |
          git config user.name "Your abhisek730"
          git config user.email "abhi.ag.kas@gmail.com"

      - name: Add GitLab remote
        run: |
          git remote add gitlab https://oauth2:glpat-wPvGW8AndrDwcwKAoc9P@gitlab.com/abhishek73025/test_repo.git

      - name: Pull changes from GitLab
        run: git pull gitlab main --rebase  # Pulls the latest changes from GitLab to avoid conflicts

      - name: Push changes to GitLab
        run: git push gitlab main  # Pushes to GitLab's main branch
