name: Sync GitHub to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync_job:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Step 2: Set up Git configuration
      - name: Set up Git configuration
        run: |
          git config user.name "abhisek730"
          git config user.email "abhi.ag.kas@gmail.com"

      # Step 3: Add GitLab remote using a secure GitLab token stored in Secrets
      - name: Add GitLab remote
        run: |
          git remote add gitlab https://oauth2:glpat-wPvGW8AndrDwcwKAoc9P@gitlab.com/abhishek73025/test_repo.git

      # Step 4: Fetch latest changes from GitLab and rebase
      - name: Fetch and rebase GitLab main branch
        run: |
          git fetch gitlab main
          git checkout main
          git rebase gitlab/main  # Rebase GitHub's main onto GitLab's main

      # Step 5: Handle conflicts (if any)
      - name: Handle merge conflicts (auto-resolve)
        run: |
          git checkout --theirs README.md  # Use GitHub's version for README conflicts
          git add README.md || true  # Only if README.md has conflicts
          git rebase --continue || true  # If rebase fails, continue if possible

      # Step 6: Push changes to GitLab
      - name: Push changes to GitLab
        run: |
          git push gitlab main  # Push changes to GitLab after rebase
